default_platform(:ios)

platform :ios do
  lane :build_only do
    build_app(
      workspace: "tone_hunter.xcworkspace",
      scheme: "tone_hunter",
      export_method: "app-store",
      output_directory: "./build/ipa",
      output_name: "tone_hunter.ipa"
    )
  end
end

