default_platform(:ios)

lane :build_only do
  gym(
    scheme: "tone_hunter",
    workspace: "tone_hunter.xcworkspace",
    export_method: "app-store",
    export_options: "ExportOptions.plist",
    clean: true,
    silent: false,
    xcargs: "-verbose -allowProvisioningUpdates",
    disable_xcpretty: true
  )
end
