default_platform(:ios)

lane :build_only do
  gym(
    scheme: "tone_hunter",
    workspace: "tone_hunter.xcworkspace",
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
        "org.reactjs.native.example.tone-hunter" => "ToneHunter Release Profile"
      },
      signingStyle: "manual",
      teamID: ENV["DEVELOPMENT_TEAM"]
    },
    clean: true,
    silent: false,
    xcargs: "-verbose",
  )
end
