default_platform(:ios)

lane :build_only do
  gym(
    scheme: "tone_hunter",
    workspace: "tone_hunter.xcworkspace",
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
        "org.reactjs.native.example.tone-hunter" => "ToneHunter Release Profile"
      }
    },
    clean: true,
    silent: false,
  )
end
